version: "3.8"

services:
  postgres:
    image: postgres
    container_name: synapsedb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=cr7#thegreat
      - POSTGRES_DB=synapseDB
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
